services:
  - type: web
    name: healthmate-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FIREBASE_CREDENTIALS
        value: <YOUR_FIREBASE_CREDENTIALS_JSON>
