# Exported from Render on 2025-01-16T05:02:39Z
services:
- type: web
  name: suryajithsurendran
  runtime: python
  repo: https://github.com/suryajithsurendran/suryajithsurendran
  plan: free
  region: oregon
  buildCommand: pip install -r requirements.txt
  startCommand: healthmaterppg.vercel.app
version: "1"
